### ISSUE TITLE
ctor function & access modifiers.

### ISSUE THREAD

**Issue by WebXScripts** [Pantoflarz/netspeakapi-php#1]
Isnt it better to load parameters immediately in the constructor of the object?
```php
function __construct($api_key, $teamspeak_api_key){
	$this->configuration['api_key'] = $api_key;
	$this->configuration['teamspeak_api_key'] = $teamspeak_api_key;
}

$netspeak = new netspeakapi("netspeak_api", "teamspeak_api");
```

I also suggest adding access modifiers (public, private) to existing class functions.

**Comment by Pantoflarz** [comment]
Sorry, I didn't get a notification about this!

The reason they are not loaded in this way, is because, as per the read.me, you don't actually need to provide them both.

You can either provide one or the other (for example, people who don't upload their terms or service do not have access to the shop key).

The reason it is split, is to make sure that people don't get confused and they know exactly what they are working with.

I don't particularly see any reason why they can't be in the constructor, but I also see no reason for it.

If its speed you are after, you shouldn't be writing in PHP in the first place, and this has negligible impact on speed :)

**Comment by Pantoflarz** [comment]
Okay, I'll take that as a no.

Closing.
